common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string  $fname
 * @property string $lname
 * @property string $mobile
 * @property integer $is_avatar_set
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        	[['fname', 'lname'], 'string', 'max' => 30],
        	[['mobile'],'string','max'=>20],
        	[['mobile'], 'udokmeci\yii2PhoneValidator\PhoneValidator','strict'=>false,'format'=>true],


        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

}

frontend/controllers/UserController.php
<?php
namespace frontend\controllers;

use Yii;
use frontend\models\UserProfileForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use yii\web\JsonParser;
use yii\helpers\Json;
use common\models\User;
use frontend\models\frontend\models;

/**
 * Site controller
 */
class UserController extends Controller
{

	/**
	 * (non-PHPdoc)
	 * @see \yii\base\Component::behaviors()
	 */

	public function behaviors()
	{
		//allow access to only authorized users
		return [
				'access' => [
						'class' => \yii\filters\AccessControl::className(),
						'only' => ['profile', 'profilePic','setAvatar'],
						'rules' => [
								// allow authenticated users
								[
										'allow' => true,
										'roles' => ['@'],
								],
								// everything else is denied
						],
				],
		];
	}

	/**
	 * show user profile
	 *
	 */
	public function actionProfile()
	{
		$session = \Yii::$app->session;
		$session->open();
		$id = $session->get ( 'userId' );

		if (! empty ( $post = Yii::$app->request->post () )) {

			// request for delete profile
			if (! empty ( $post ['delete-profile'] )) {

				$model = User::findIdentity($id);
				$model->status = User::STATUS_DELETED;

				//update user status in db
				if($model->save()) {
					\Yii::$app->getSession()->setFlash('success', 'Your account has been delete.');
					return $this->redirect('/site/logout');
				}
				else { //error received
					\Yii::$app->getSession()->setFlash('error', 'Error while deleting your account!!');
				}

			} else { //request for update profile

				$post = Yii::$app->request->post ();
				$userProfile = $post ['UserProfileForm'];

				$model = User::findIdentity ( $id );
				$model->fname = $userProfile ['fname'];
				$model->lname = $userProfile ['lname'];
				$model->mobile = $userProfile ['mobile'];

				if ($model->save())
					\Yii::$app->getSession ()->setFlash ( 'success', 'Profile has been updated.' );
				else {
					\Yii::$app->getSession ()->setFlash ( 'error', 'Error while updating profile!!' );
				}
			}
		}

		$model = UserProfileForm::loadModel ( $id );
		return $this->render ( 'profile', [
				'model' => $model
		] );
	}

	/**
	 * function uploads file to a temporary folder to be croped afterward.
	 *
	 * @return string
	 */
	public function actionProfilePic() {

		$session =\Yii::$app->session;
		$session->open();
		$random = $session->getId() . rand(1,100);
		$imageFile = UploadedFile::getInstanceByName('UserProfileForm[profilePic]');
		$profileUrl = '/img/temp/';
		$directory = \Yii::getAlias('@'.\Yii::$app->params['avatarTempDir']);
		if (!is_dir($directory)) {
			mkdir($directory);
		}
		if ($imageFile)	 {

			$filePath = $directory .$random ;
			if ($imageFile->saveAs($filePath)) {
				chmod($filePath, 0777);
				return  $profileUrl.$random;
			}
		}
		return '';

	}

	/**
	 * function crops the file and uploads to its final destination.
	 */
	public function actionSetAvatar() {

		$session =\Yii::$app->session;
		$session->open();
		$sessionId = $session->getId();
		$newname = \Yii::getAlias('@'.\Yii::$app->params['avatarDir']).$session->get('userId').'.jpeg';

		//get the filename from the post data
		$request = Yii::$app->request;
		$filename = end(explode('/',$request->post('path')));

		$imageSource = \Yii::getAlias('@'.\Yii::$app->params['avatarTempDir']).$filename;
		$avatarUrl = '/img/avatar/'.$session->get('userId').'.jpeg?'.rand(1,100);

		//gather x and y cordinates of croped region
		$x1 = empty($request->post('x1'))?0:$request->post('x1');
		$x2 = empty($request->post('x2'))?0:$request->post('x2');
		$y1 = empty($request->post('y1'))?0:$request->post('y1');
		$y2 = empty($request->post('y2'))?0:$request->post('y2');

		$h = $request->post('h');
		$w = $request->post('w');

		// nothing cropped
		if (empty($w)) {
			if(file_exists($newname)) {
				@unlink($newname);
			}
			copy($imageSource, $newname);
			@unlink($imageSource);
		}
		else {

			$imageHeight = $request->post ( 'image_height' );
			$imageWidth = $request->post ( 'image_width' );

			//crop image
			$imagick = new \Imagick($imageSource);
			$imagick->cropImage($x2-$x1, $y2-$y1, $x1, $y1);

			//resize to orinal display
			$imagick->resizeImage($imageWidth, $imageHeight,\Imagick::FILTER_LANCZOS, 0.9);
			//delete file if already exists
			if(file_exists($newname)) {
				@unlink($newname);
			}
			//save file on the disk
			file_put_contents($newname, $imagick);

		}
		//Get user model
		$user = User::findIdentity($session->get('userId'));

		//update value of avatar if it is unset
		if($user->is_avatar_set == 0) {
			$user->is_avatar_set = 1;
			$user->save();
		}

		$response['url'] = $avatarUrl;
		return Json::encode($response,true);
	}

}

frontend/views/user/profile.php
<?php

use dosamigos\fileupload\FileUpload;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

//include profile.js file -> depends on jquery
$this->registerJsFile('@web/js/profile.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

$width = $height = 200;
$maxWidth = 400;
$altText = "Avatar";
$imageSource = $model->profilePic;

$this->title = 'Profile';
$this->params['breadcrumbs'][] = $this->title;


?>

<?=
	\cozumel\cropper\ImageCropper::widget(['id' => 'user_profile_photo']);

?>

<img width="<?= $width; ?>" height="<?= $height; ?>" max-width="<?=$maxWidth;?>" class="border" id="user_profile_photo" alt="<?=$altText;?>" src="<?= $imageSource; ?>">
<div style='height: 10px;width:100%'></div>
<?=
	FileUpload::widget([
    'model' => $model,
    'attribute' => 'profilePic',
    'url' => ['user/profile-pic'],
    'options' => ['accept' => 'image/*'],
    'clientOptions' => [
        'maxFileSize' => 2000000
    ],

    // Also, you can specify jQuery-File-Upload events
    // see: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#processing-callback-options
    'clientEvents' => [
        'fileuploaddone' => 'onFileUploadSuccess',
        'fileuploadfail' => 'onFileUploadFail',
    ],
]);?>
<?php
$form = ActiveForm::begin(['action' => Yii::$app->urlManager->createUrl(['user/set-avatar']),
		'options' => ['id' => 'crop_form'],
]);
?>
<div><input type="hidden" id="x1" value="" name="x1"></div>

<div><input type="hidden" id="y1" value="" name="y1"></div>
<div><input type="hidden" id="x2" value="" name="x2"></div>
<div><input type="hidden" id="y2" value="" name="y2"></div>
<div><input type="hidden" id="w" value="" name="w"></div>
<div><input type="hidden" id="h" value="" name="h"></div>
<div><input type="hidden" value="<?= $width; ?>" name="image_width"></div>
<div><input type="hidden" value="<?= $height; ?>" name="image_height"></div>
<div><input type="hidden" id="profile_path" value="" name="path"></div>
<div style="margin-top:10px;">

<div class="form-group">
     <?= Html::submitButton('Crop and Save', ['class' => 'btn btn-primary', 'name' => 'save-profile','style' => "visibility:hidden" , 'id'=>"js_save_profile_photo"]) ?>
</div>

<input type="submit" class="button" style="visibility:hidden" id="js_save_profile_photo" value="Crop and Sve">
</div>

<?php ActiveForm::end(); ?>

<div class="row">
        <div class="col-lg-5">
           <?php
			$form = ActiveForm::begin(['action' => Yii::$app->urlManager->createUrl(['user/profile']), 'options' => ['id' => 'profile_form'],
]);
?>
                <?= $form->field($model, 'fname')->textInput(['maxlength'=>30]); ?>
                <?= $form->field($model, 'lname')->textInput(['maxlength'=>30]) ?>
                <?= $form->field($model, 'email')->textInput(['readonly' => true]) ?>
                <?= $form->field($model, 'mobile')->textInput(['maxlength'=>20]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Update Profile', ['class' => 'btn btn-primary', 'name' => 'save-profile', 'value'=>'1']) ?>
                    <?= Html::submitButton('Delete Profile', ['class' => 'btn btn-primary', 'name' => 'delete-profile' , 'value'=>'1']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

frontend/views/user/profile2.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$width = $height = 100;
$max_width = 250;
$alt_text = "No file";
$image_source = '/';

?>
<?= \cozumel\cropper\ImageCropper::widget(['id' => 'user_profile_photo']); ?>

<img width="<?= $width; ?>" height="<?= $height; ?>" max-width="<?=$max_width;?>" class="border" id="user_profile_photo" alt="<?=$alt_text;?>" src="<?= $image_source; ?>">
<?php


$form = ActiveForm::begin(['action' => Yii::$app->urlManager->createUrl(['your/url/here']), 'options' => ['id' => 'crop_form'],
]);
?>
<div><input type="hidden" id="x1" value="" name="x1"></div>
<div><input type="hidden" id="y1" value="" name="y1"></div>
<div><input type="hidden" id="x2" value="" name="x2"></div>
<div><input type="hidden" id="y2" value="" name="y2"></div>
<div><input type="hidden" id="w" value="" name="w"></div>
<div><input type="hidden" id="h" value="" name="h"></div>
<div><input type="hidden" value="<?= $width; ?>" name="image_width"></div>
<div><input type="hidden" value="<?= $height; ?>" name="image_height"></div>
<div style="margin-top:10px;">
<input type="submit" class="button" id="js_save_profile_photo" value="Save Avatar">
</div>

<?php ActiveForm::end(); ?>